'use strict';

try{

    let x = 10;
    // mshhhhhhhhhhiFuncion();
}
catch (error){
    console.log(error);
}
finally{
    console.log("termina la revision de errores");
}
console.log("mostrar");